MODEL:
  VID:
    METHOD: "dff"
    ROI_BOX_HEAD:
      REDUCE_CHANNEL: True
  META_ARCHITECTURE: "GeneralizedRCNNDFF"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNetConv52MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)