MODEL:
  VID:
    METHOD: "fgfa"
  META_ARCHITECTURE: "GeneralizedRCNNFGFA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNetConv52MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)